version: "3.1"
services:
  postgres:
    image: jeugenio/postgres-13.3-alpine
    container_name: postgres-13.3-alpine
    working_dir: /application
    volumes:
      - .:/application
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=YOUR_PASSWORD
      - POSTGRES_DB=YOUR_NAME_DATABASE
    ports:
      - "5432:5432"
